version: '3.1'

services:

  db:
    container_name: tpo-app-interact-mysql
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_interact_tpo
      MYSQL_USER: tpo
      MYSQL_PASSWORD: secret 
    ports:
      - 3306:3306
    volumes:
      - ./resources:/tmp/tp_sql