DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS gift_lists;
DROP TABLE IF EXISTS users;

 CREATE TABLE IF NOT EXISTS users (
   id INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(40) NOT NULL,
   email VARCHAR(40) NOT NULL,
   password VARCHAR(250) NOT NULL
 );

CREATE TABLE IF NOT EXISTS gift_lists (
  id INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  list_name VARCHAR(40) NOT NULL,
  due_date DATE NOT NULL,
  to_name VARCHAR(40) NOT NULL,
  to_mail VARCHAR(40) NOT NULL,
  owner_id INT(8) NOT NULL, 
  expected_amount FLOAT NOT NULL DEFAULT 0,
  current_amount FLOAT NOT NULL DEFAULT 0,
  delivered BIT NOT NULL DEFAULT 0,
  FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS payments (
  id INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  amount FLOAT(8,2) NOT NULL DEFAULT 0,
  payer_id INT(8) NOT NULL,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gift_list_id INT(8) NOT NULL,
  FOREIGN KEY (payer_id) REFERENCES users(id),
  FOREIGN KEY (gift_list_id) REFERENCES gift_lists(id)
);
